databases:
  - name: mysitedb
    plan: free
    databaseName: social-media-app-using-django-1
    user: social-media-app-using-django-1

services:
  - type: web
    plan: free
    name: social-media-app-using-django-1
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn social-media-app-using-django-1.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysitedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4