# Generated by Django 4.1.5 on 2024-03-26 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_username_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profileimage',
            new_name='profileimag',
        ),
    ]
