# Generated by Django 4.1.5 on 2024-03-26 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_profileimage_profile_profileimag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id_user',
        ),
    ]
